# Generated by Django 5.0.4 on 2024-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studrec',
            name='course',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('BA', 'Business Administration')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studrec',
            name='major',
            field=models.CharField(blank=True, choices=[('SE', 'Software Engineering'), ('NE', 'Network Engineering'), ('MD', 'Mechanical Design'), ('FM', 'Financial Management')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
