# Generated by Django 5.0.4 on 2024-05-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_studrec_course_alter_studrec_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studrec',
            name='course',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Business Administration', 'Business Administration')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studrec',
            name='major',
            field=models.CharField(blank=True, choices=[('Software Engineering', 'Software Engineering'), ('Network Engineering', 'Network Engineering'), ('Mechanical Design', 'Mechanical Design'), ('Financial Management', 'Financial Management')], max_length=200, null=True),
        ),
    ]
