# Generated by Django 5.0.4 on 2024-05-06 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_studrec_course_alter_studrec_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reference_id', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.studrec')),
            ],
        ),
    ]
