# Generated by Django 5.0.4 on 2024-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studrec',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
