# Generated by Django 5.0.4 on 2024-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_attendancelog_auto_created_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='auto_created',
        ),
    ]
