# Generated by Django 5.0.4 on 2024-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_attendancelog_auto_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studrec',
            name='course',
            field=models.CharField(blank=True, choices=[('Bachelor of Science in Marine Transportation', 'BSMT'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Business Administration', 'Business Administration')], max_length=200, null=True),
        ),
    ]
