# Generated by Django 5.0.4 on 2024-07-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_studrec_middle_name_alter_studrec_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='studrec',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
