# Generated by Django 5.0.4 on 2024-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_studrec_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
