# Generated by Django 5.0.4 on 2024-07-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_userprofile_is_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
