# Generated by Django 5.0.4 on 2024-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
