# Generated by Django 5.0.4 on 2024-08-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
