# Generated by Django 5.0.4 on 2024-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
