# Generated by Django 5.0.4 on 2024-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_alter_attendancelog_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
