# Generated by Django 5.0.4 on 2024-08-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_studreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studReg',
        ),
    ]
