# Generated by Django 5.0.4 on 2024-09-09 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_pendingrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='pendingrequests',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studrec',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='studrec',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
