# Generated by Django 5.0.4 on 2024-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_pendingrequests_email_pendingrequests_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='security_pictures/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
