# Generated by Django 5.0.4 on 2024-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_headofsecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('head_of_security', 'Head of Security')], default='student', max_length=20),
        ),
    ]
