# Generated by Django 5.0.4 on 2024-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_headofsecurity_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
        migrations.AddField(
            model_name='studrec',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
    ]
