# Generated by Django 5.0.4 on 2024-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_pendingrequests_username_studrec_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrequests',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studrec',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
