# Generated by Django 5.0.4 on 2024-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_alter_pendingrequests_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studrec',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
